# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12d6f4db413dd7e90b14491ad8ebcfd893d92eeca5b4f2dc08d724764d6d216156612dcd377233379f8cfe360e97e88dc37e322d7ed88b64bd3f2b0fdfa46f1f

test:
  secret_key_base: fd4a13babebd74d315866c1b01b59ea0cc05c729051408adec8ac42cd7dba925ee7fc3d76e1be6317720c41f01f7d5fd93108012154fa9dc251bcf811a32171f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
